# Generated by Django 5.1.3 on 2024-11-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_book_created_at_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='show_counter',
            field=models.IntegerField(default=0),
        ),
    ]
